### ISSUE TITLE
PR 681 changes breaks some relayer commands

### ISSUE THREAD

**Issue by ashishchandr70** [cosmos/chain-registry#699] opened 2022-09-08 23:49 UTC
I was just playing with the relayer code in `vscode` and tried to execute command `rly paths fetch` with the chains set to `cosmoshub` and `osmosis`. However, it panics each time and I think that is because of PR #681 

The `IBCData` struct still uses `dashes` for the key names in the json registry files.

See https://github.com/cosmos/relayer/blob/ffc46dc11b306b5673b7ca03ce5c4ee77ce4ce57/relayer/path.go#L105 for reference.

Here is the error.
![image](https://user-images.githubusercontent.com/41921015/189245712-0742fd32-22b2-4b38-bab7-388a687ca774.png)

**Comment by JeremyParish69** [comment] 2022-09-10 03:43
hi @ashishchandr70 , thanks for bringing this up.

For now, I believe reverting the change may resolve your issue, and likely not impact anything else built around the underscores, since it is a recent change. However, I believe the issue that called for that change has some validity. I'm wondering (and hoping) that a PR to update that struct at the same time can resolve this and prevent issues like this in the future...

**Comment by JeremyParish69** [comment] 2022-09-15 00:17
> @JeremyParish69 thanks for your response. Would the PR be created by someone on the `relayer` team? Should I close this issue or leave it open?

I submitted a PR that has been merged. I might wait a couple days before closing to see if anyone (you?) can confirm that the issue is truly resolved.

**Closed** 2022-10-16 21:40 UTC
